#!/usr/bin/perl -w
# season-zeropad <tv-dir>

use strict;
use Data::Dumper;

die "./season-zeropad <tv-dir>" unless defined $ARGV[0];

my $base_dir = $ARGV[0];

if (!-d $base_dir) {
	die "No such dir";	
}
chdir($base_dir);

opendir DIR, ".";
my @rename = ();

while(my $item = readdir DIR) {
	if ($item !~ /^\./) {
		if (-d $item) {
			opendir(my $subdir, $item);
			while(my $subitem = readdir $subdir) {
				if ($subitem =~ /^Season (\d+)/i) {
					my $from = $item."/".$subitem;
					my $to = $item."/Season ".sprintf("%02d",$1);
	
					push @rename, [$from, $to] if ($from ne $to);
				}
			}
			closedir $subdir;
		}
	}
}

closedir DIR;

print Dumper \@rename;

print "PRESS CTRL+C TO ABORT, OR ANYKEY TO CONTINUE\n";

my $c = getc(STDIN);	

foreach my $r (@rename) {

	if (-d $r->[1]) {
		print "Skipping ".$r->[0]." as ".$r->[1]." exists.\n";
	} else {
		print "Renaming ".$r->[0]." to ".$r->[1]."\n";
		rename $r->[0], $r->[1] or die "Unable to rename: $!";
	}
}

print "\n";

