#!/usr/bin/perl -w
# file-flags <tv-dir>

use strict;
use Data::Dumper;

die "./subfolders <tv-dir>" unless defined $ARGV[0];
our @unlink;

my $base_dir = $ARGV[0];

if (!-d $base_dir) {
	die "No such dir";	
}
chdir($base_dir);

opendir DIR, ".";
my @rename = ();

while(my $item = readdir DIR) {
	if ($item !~ /^\./) {
		if (-d $item) {
			opendir(my $seasonhandle, $item);
			while(my $seasonfolder = readdir $seasonhandle) {
				if ($seasonfolder =~ /^Season (\d+)$/i) {
					opendir(my $filehandle, $item."/".$seasonfolder);
					FILE: while (my $filename = readdir $filehandle) {
						next FILE if ($filename =~ /^\./);
						my $fpath = $item."/".$seasonfolder."/".$filename;
						if (! -f $fpath) {
							print $fpath."\n";
						}
					}

					closedir $filehandle;
				}
			}
			closedir $seasonhandle;
		}
	}
}

sub multitrim {
	my @r = ();
	for my $i (@_) {
		$i =~ s/^\s+//gs;
		$i =~ s/\s+$//gs;
		$i =~ s/\s+-+\s+$//gs;
		push @r, $i;
	}
	return @r;
}

closedir DIR;


# 
# print Dumper \@unlink;
# print "FILES FOR DELETION. CTRL+C TO CANCEL\n";
# 
# getc(STDIN);
# 
# foreach my $path (@unlink) {
# 	print "DELETING $path\n";
# 	unlink $path or die "Cant delete $path: $!";
# }
# 
# 
# 

sub queue_unlink {
	my ($path) = @_;
	push @unlink, $path;

}
